M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu22.04.1} date Sat 11 Nov 2023 15:45:26
; FORMAT={2:4/ absolute / inch / suppress leading zeros}
; #@! TF.CreationDate,2023-11-11T15:45:26+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X25500Y-11000
X25500Y-40000
X84000Y-11000
X84000Y-40000
T2
X40750Y-35425
T0
M30
